const INTERACTIVE_LESSONS_DATA = [
    {
        "name":  "mshy112025m.html",
        "title":  "Mshy112025m",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "34.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/mshy112025m.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%2011%20Qp%20HY%20KVR%202025/mshy112025m.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\Class 11 Qp HY KVR 2025\\mshy112025m.html"
    },
    {
        "name":  "binomial theorem.html",
        "title":  "Binomial Theorem",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "4.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/binomial theorem.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/class%20test/binomial%20theorem.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\class test\\binomial theorem.html"
    },
    {
        "name":  "class test analysis.html",
        "title":  "Class Test Analysis",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "15.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/class test analysis.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/class%20test/class%20test%20analysis.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\class test\\class test analysis.html"
    },
    {
        "name":  "sequence and series.html",
        "title":  "Sequence And Series",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "5.1 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/sequence and series.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/class%20test/sequence%20and%20series.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\class test\\sequence and series.html"
    },
    {
        "name":  "CH 1 SETS.html",
        "title":  "Chapter 1 Sets",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "24.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/CH 1 SETS.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20html%20file/CH%201%20SETS.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive html file\\CH 1 SETS.html"
    },
    {
        "name":  "CH 3 T FUNCTIONS.html",
        "title":  "Chapter 3 T Functions",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "26.3 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/CH 3 T FUNCTIONS.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20html%20file/CH%203%20T%20FUNCTIONS.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive html file\\CH 3 T FUNCTIONS.html"
    },
    {
        "name":  "CH 5 LINEAR INEQUALITIES.html",
        "title":  "Chapter 5 Linear Inequalities",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "54.7 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/CH 5 LINEAR INEQUALITIES.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20html%20file/CH%205%20LINEAR%20INEQUALITIES.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive html file\\CH 5 LINEAR INEQUALITIES.html"
    },
    {
        "name":  "CH 3 T FUNCTIONS.png",
        "title":  "Chapter 3 T Functions",
        "category":  "infographics",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "4.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive infographics/CH 3 T FUNCTIONS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20infographics/CH%203%20T%20FUNCTIONS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive infographics\\CH 3 T FUNCTIONS.png"
    },
    {
        "name":  "CH 4 COMPLEX NUMBERS.png",
        "title":  "Chapter 4 Complex Numbers",
        "category":  "infographics",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "4.4 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive infographics/CH 4 COMPLEX NUMBERS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20infographics/CH%204%20COMPLEX%20NUMBERS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive infographics\\CH 4 COMPLEX NUMBERS.png"
    },
    {
        "name":  "CH 5 LINEAR INEQUALITIES.png",
        "title":  "Chapter 5 Linear Inequalities",
        "category":  "infographics",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "4.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive infographics/CH 5 LINEAR INEQUALITIES.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20infographics/CH%205%20LINEAR%20INEQUALITIES.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive infographics\\CH 5 LINEAR INEQUALITIES.png"
    },
    {
        "name":  "CH 6 PERMUTATIONS AND COMBINATIONS.png",
        "title":  "Chapter 6 Permutations And Combinations",
        "category":  "infographics",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "4.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive infographics/CH 6 PERMUTATIONS AND COMBINATIONS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20infographics/CH%206%20PERMUTATIONS%20AND%20COMBINATIONS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive infographics\\CH 6 PERMUTATIONS AND COMBINATIONS.png"
    },
    {
        "name":  "CH 3 T FUNCTIONS.pptx",
        "title":  "Chapter 3 T Functions",
        "category":  "slides",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "20.4 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive ppt slide deck/CH 3 T FUNCTIONS.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20ppt%20slide%20deck/CH%203%20T%20FUNCTIONS.pptx",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive ppt slide deck\\CH 3 T FUNCTIONS.pptx"
    },
    {
        "name":  "CH 4 COMPLEX NUMBERS.pptx",
        "title":  "Chapter 4 Complex Numbers",
        "category":  "slides",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "14.7 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive ppt slide deck/CH 4 COMPLEX NUMBERS.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20ppt%20slide%20deck/CH%204%20COMPLEX%20NUMBERS.pptx",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive ppt slide deck\\CH 4 COMPLEX NUMBERS.pptx"
    },
    {
        "name":  "CH 5 LINEAR INEQUALITIES.pptx",
        "title":  "Chapter 5 Linear Inequalities",
        "category":  "slides",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "17.1 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive ppt slide deck/CH 5 LINEAR INEQUALITIES.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20ppt%20slide%20deck/CH%205%20LINEAR%20INEQUALITIES.pptx",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive ppt slide deck\\CH 5 LINEAR INEQUALITIES.pptx"
    },
    {
        "name":  "CH6 PERMUTATIONS AND COMBINATIONS.pptx",
        "title":  "Ch6 Permutations And Combinations",
        "category":  "slides",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "15.5 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive ppt slide deck/CH6 PERMUTATIONS AND COMBINATIONS.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20ppt%20slide%20deck/CH6%20PERMUTATIONS%20AND%20COMBINATIONS.pptx",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive ppt slide deck\\CH6 PERMUTATIONS AND COMBINATIONS.pptx"
    },
    {
        "name":  "CH 3 T FUNCTIONS.mp4",
        "title":  "Chapter 3 T Functions",
        "category":  "videos",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "51.4 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive vedio/CH 3 T FUNCTIONS.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20vedio/CH%203%20T%20FUNCTIONS.mp4",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive vedio\\CH 3 T FUNCTIONS.mp4"
    },
    {
        "name":  "CH 4 COMPLEX NUMBERS.mp4",
        "title":  "Chapter 4 Complex Numbers",
        "category":  "videos",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "31.9 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive vedio/CH 4 COMPLEX NUMBERS.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20vedio/CH%204%20COMPLEX%20NUMBERS.mp4",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive vedio\\CH 4 COMPLEX NUMBERS.mp4"
    },
    {
        "name":  "CH 6 PERMUATTIONS AND COMBINATIONS.mp4",
        "title":  "Chapter 6 Permuattions And Combinations",
        "category":  "videos",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "38.4 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/interactive vedio/CH 6 PERMUATTIONS AND COMBINATIONS.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/interactive%20vedio/CH%206%20PERMUATTIONS%20AND%20COMBINATIONS.mp4",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\interactive vedio\\CH 6 PERMUATTIONS AND COMBINATIONS.mp4"
    },
    {
        "name":  "CH 1 SETS.png",
        "title":  "Chapter 1 Sets",
        "category":  "mindmaps",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "1.9 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/mind map/CH 1 SETS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/mind%20map/CH%201%20SETS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\mind map\\CH 1 SETS.png"
    },
    {
        "name":  "CH 2 TRELATIONS AND FUNCTIONS.png",
        "title":  "Chapter 2 Trelations And Functions",
        "category":  "mindmaps",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "1.4 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/mind map/CH 2 TRELATIONS AND FUNCTIONS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/mind%20map/CH%202%20TRELATIONS%20AND%20FUNCTIONS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\mind map\\CH 2 TRELATIONS AND FUNCTIONS.png"
    },
    {
        "name":  "CH 3 T FUNCTIONS.png",
        "title":  "Chapter 3 T Functions",
        "category":  "mindmaps",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "1.6 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/mind map/CH 3 T FUNCTIONS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/mind%20map/CH%203%20T%20FUNCTIONS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\mind map\\CH 3 T FUNCTIONS.png"
    },
    {
        "name":  "CH 4 COMPLEX NUMBERS.png",
        "title":  "Chapter 4 Complex Numbers",
        "category":  "mindmaps",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "1.5 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/mind map/CH 4 COMPLEX NUMBERS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/mind%20map/CH%204%20COMPLEX%20NUMBERS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\mind map\\CH 4 COMPLEX NUMBERS.png"
    },
    {
        "name":  "CH 5 LINEAR INEQUALITIES.png",
        "title":  "Chapter 5 Linear Inequalities",
        "category":  "mindmaps",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "948.9 KB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/mind map/CH 5 LINEAR INEQUALITIES.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/mind%20map/CH%205%20LINEAR%20INEQUALITIES.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\mind map\\CH 5 LINEAR INEQUALITIES.png"
    },
    {
        "name":  "CH 6 PERMUTATIONS AND COMBINATIONS.png",
        "title":  "Chapter 6 Permutations And Combinations",
        "category":  "mindmaps",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "924.3 KB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/11 ALL TEACHING LEARNING CONTENT/interactive plans/mind map/CH 6 PERMUTATIONS AND COMBINATIONS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20plans/mind%20map/CH%206%20PERMUTATIONS%20AND%20COMBINATIONS.png",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\interactive plans\\mind map\\CH 6 PERMUTATIONS AND COMBINATIONS.png"
    },
    {
        "name":  "lesson plan ellipse.html",
        "title":  "Lesson Plan Ellipse",
        "category":  "html",
        "class":  "Class 11",
        "classKey":  "class11",
        "size":  "19.3 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class11/lesson plan ellipse.html",
        "dropboxUrl":  "https://www.dropbox.com/home/11%20ALL%20TEACHING%20LEARNING%20CONTENT/misc/lesson%20plan%20ellipse.html",
        "path":  "11 ALL TEACHING LEARNING CONTENT\\misc\\lesson plan ellipse.html"
    },
    {
        "name":  "activity 10.html",
        "title":  "Activity 10",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "10.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/activity 10.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Activities/activity%2010.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Activities\\activity 10.html"
    },
    {
        "name":  "activity 8.html",
        "title":  "Activity 8",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "13.2 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/activity 8.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Activities/activity%208.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Activities\\activity 8.html"
    },
    {
        "name":  "activity 9.html",
        "title":  "Activity 9",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "11.4 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/activity 9.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Activities/activity%209.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Activities\\activity 9.html"
    },
    {
        "name":  "3 Dimensional Geo.html",
        "title":  "3 Dimensional Geo",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "5.3 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/3 Dimensional Geo.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Tests/3%20Dimensional%20Geo.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Class Tests\\3 Dimensional Geo.html"
    },
    {
        "name":  "probability test.html",
        "title":  "Probability Test",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "5.6 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/probability test.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Tests/probability%20test.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Class Tests\\probability test.html"
    },
    {
        "name":  "test record html for class 12.html",
        "title":  "Test Record Html For Class 12",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "19.1 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/test record html for class 12.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Tests/test%20record%20html%20for%20class%2012.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Class Tests\\test record html for class 12.html"
    },
    {
        "name":  "Vector Algebra CT.html",
        "title":  "Vector Algebra Ct",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "7.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/Vector Algebra CT.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Tests/Vector%20Algebra%20CT.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Class Tests\\Vector Algebra CT.html"
    },
    {
        "name":  "casebasedquestion3d.html",
        "title":  "Casebasedquestion3d",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "44.3 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/casebasedquestion3d.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Inspection%20day%20plan/casebasedquestion3d.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Inspection day plan\\casebasedquestion3d.html"
    },
    {
        "name":  "heights and distance.html",
        "title":  "Heights And Distance",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "32.1 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/heights and distance.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Inspection%20day%20plan/heights%20and%20distance.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Inspection day plan\\heights and distance.html"
    },
    {
        "name":  "casebasedquestion3d.html",
        "title":  "Casebasedquestion3d",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "39.4 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/casebasedquestion3d.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Inspection%20day%20plan/desktop%20version/casebasedquestion3d.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Inspection day plan\\desktop version\\casebasedquestion3d.html"
    },
    {
        "name":  "lessonplan9oct3d.html",
        "title":  "Lessonplan9oct3d",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "31.3 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/lessonplan9oct3d.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Inspection%20day%20plan/desktop%20version/lessonplan9oct3d.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Inspection day plan\\desktop version\\lessonplan9oct3d.html"
    },
    {
        "name":  "cbq question.html",
        "title":  "Cbq Question",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "41.3 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/cbq question.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/Inspection%20day%20plan/mobile%20version/cbq%20question.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\Inspection day plan\\mobile version\\cbq question.html"
    },
    {
        "name":  "12 maths study material.html",
        "title":  "12 Maths Study Material",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "79.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/12 maths study material.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/12%20maths%20study%20material.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\12 maths study material.html"
    },
    {
        "name":  "7 days revision plan class 12 maths.html",
        "title":  "7 Days Revision Plan Class 12 Maths",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "70.6 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/7 days revision plan class 12 maths.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/7%20days%20revision%20plan%20class%2012%20maths.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\7 days revision plan class 12 maths.html"
    },
    {
        "name":  "CH 2 INVERSE T FUNCTIONS HTML.html",
        "title":  "Chapter 2 Inverse T Functions",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "26.7 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/CH 2 INVERSE T FUNCTIONS HTML.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/CH%202%20INVERSE%20T%20FUNCTIONS%20HTML.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\CH 2 INVERSE T FUNCTIONS HTML.html"
    },
    {
        "name":  "CH 3 MATRICES HTML.html",
        "title":  "Chapter 3 Matrices",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "30.1 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/CH 3 MATRICES HTML.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/CH%203%20MATRICES%20HTML.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\CH 3 MATRICES HTML.html"
    },
    {
        "name":  "CH 4 DETERMINANTS HTML.html",
        "title":  "Chapter 4 Determinants",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "24.2 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/CH 4 DETERMINANTS HTML.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/CH%204%20DETERMINANTS%20HTML.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\CH 4 DETERMINANTS HTML.html"
    },
    {
        "name":  "CH 5 CONTINUITY AND DIFF HTML.html",
        "title":  "Chapter 5 Continuity And Diff",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "27.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/CH 5 CONTINUITY AND DIFF HTML.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/CH%205%20CONTINUITY%20AND%20DIFF%20HTML.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\CH 5 CONTINUITY AND DIFF HTML.html"
    },
    {
        "name":  "CH 7 INTEGRALS HTML.html",
        "title":  "Chapter 7 Integrals",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "52.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/CH 7 INTEGRALS HTML.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/CH%207%20INTEGRALS%20HTML.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\CH 7 INTEGRALS HTML.html"
    },
    {
        "name":  "LP1.html",
        "title":  "Lp1",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "18.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/LP1.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/LP1.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\LP1.html"
    },
    {
        "name":  "LP2.html",
        "title":  "Lp2",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "34.4 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/LP2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/LP2.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\LP2.html"
    },
    {
        "name":  "MATHS CLASS 12 STUDY MATERIAL.html",
        "title":  "Maths Class 12 Study Material",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "93 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/MATHS CLASS 12 STUDY MATERIAL.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/MATHS%20CLASS%2012%20STUDY%20MATERIAL.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\MATHS CLASS 12 STUDY MATERIAL.html"
    },
    {
        "name":  "Preboard class 12 summer.html",
        "title":  "Preboard Class 12 Summer",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "42.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/Preboard class 12 summer.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20HTML/Preboard%20class%2012%20summer.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE HTML\\Preboard class 12 summer.html"
    },
    {
        "name":  "CH 1 RELATIONS AND FN INFG.png",
        "title":  "Chapter 1 Relations And Fn",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "5.1 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 1 RELATIONS AND FN INFG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%201%20RELATIONS%20AND%20FN%20INFG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 1 RELATIONS AND FN INFG.png"
    },
    {
        "name":  "CH 10 VECTORS INFOG.png",
        "title":  "Chapter 10 Vectors",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "4.1 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 10 VECTORS INFOG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%2010%20VECTORS%20INFOG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 10 VECTORS INFOG.png"
    },
    {
        "name":  "CH 11 3-D INFOG.png",
        "title":  "Chapter 11 3 D",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "4.4 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 11 3-D INFOG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%2011%203-D%20INFOG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 11 3-D INFOG.png"
    },
    {
        "name":  "CH 12 LPP INFOG.png",
        "title":  "Chapter 12 Lpp",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "4.5 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 12 LPP INFOG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%2012%20LPP%20INFOG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 12 LPP INFOG.png"
    },
    {
        "name":  "CH 13 PROBABILITY INFOG.png",
        "title":  "Chapter 13 Probability",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "4.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 13 PROBABILITY INFOG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%2013%20PROBABILITY%20INFOG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 13 PROBABILITY INFOG.png"
    },
    {
        "name":  "CH 2 INVERSE T FUNCTIONS INFG.png",
        "title":  "Chapter 2 Inverse T Functions",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.7 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 2 INVERSE T FUNCTIONS INFG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%202%20INVERSE%20T%20FUNCTIONS%20INFG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 2 INVERSE T FUNCTIONS INFG.png"
    },
    {
        "name":  "CH 3 MATRICES INFG.png",
        "title":  "Chapter 3 Matrices",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "4 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 3 MATRICES INFG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%203%20MATRICES%20INFG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 3 MATRICES INFG.png"
    },
    {
        "name":  "CH 4 DETERMINANTS INFG.png",
        "title":  "Chapter 4 Determinants",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "4.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 4 DETERMINANTS INFG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%204%20DETERMINANTS%20INFG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 4 DETERMINANTS INFG.png"
    },
    {
        "name":  "CH 7 INTEGRALS.png",
        "title":  "Chapter 7 Integrals",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "4.3 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 7 INTEGRALS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%207%20INTEGRALS.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 7 INTEGRALS.png"
    },
    {
        "name":  "CH 8 APPLICATION OF INTEGRALS.png",
        "title":  "Chapter 8 Application Of Integrals",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "3.7 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 8 APPLICATION OF INTEGRALS.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%208%20APPLICATION%20OF%20INTEGRALS.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 8 APPLICATION OF INTEGRALS.png"
    },
    {
        "name":  "CH 9 DIIF EQ INFOG.png",
        "title":  "Chapter 9 Diif Eq",
        "category":  "infographics",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "5 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE INFOGRAPHICS/CH 9 DIIF EQ INFOG.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20INFOGRAPHICS/CH%209%20DIIF%20EQ%20INFOG.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE INFOGRAPHICS\\CH 9 DIIF EQ INFOG.png"
    },
    {
        "name":  "CH 1 RELATIONS AND FN MIND MAP.png",
        "title":  "Chapter 1 Relations And Fn Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "907.5 KB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 1 RELATIONS AND FN MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%201%20RELATIONS%20AND%20FN%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 1 RELATIONS AND FN MIND MAP.png"
    },
    {
        "name":  "CH 10 VECTOR MIND MAP.png",
        "title":  "Chapter 10 Vector Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "2.1 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 10 VECTOR MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%2010%20VECTOR%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 10 VECTOR MIND MAP.png"
    },
    {
        "name":  "CH 11 3-D MIND MAP.png",
        "title":  "Chapter 11 3 D Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 11 3-D MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%2011%203-D%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 11 3-D MIND MAP.png"
    },
    {
        "name":  "CH 12 LPP MIND MAP.png",
        "title":  "Chapter 12 Lpp Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.1 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 12 LPP MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%2012%20LPP%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 12 LPP MIND MAP.png"
    },
    {
        "name":  "CH 13 PROBABILITY MIND MAP.png",
        "title":  "Chapter 13 Probability Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.1 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 13 PROBABILITY MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%2013%20PROBABILITY%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 13 PROBABILITY MIND MAP.png"
    },
    {
        "name":  "CH 2 INVERSE T FUN MIND MAP.png",
        "title":  "Chapter 2 Inverse T Fun Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "3.9 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 2 INVERSE T FUN MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%202%20INVERSE%20T%20FUN%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 2 INVERSE T FUN MIND MAP.png"
    },
    {
        "name":  "CH 3 MATRICES MIND MAP.png",
        "title":  "Chapter 3 Matrices Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.4 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 3 MATRICES MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%203%20MATRICES%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 3 MATRICES MIND MAP.png"
    },
    {
        "name":  "CH 4 DETERMINANTS MIND MAP.png",
        "title":  "Chapter 4 Determinants Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 4 DETERMINANTS MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%204%20DETERMINANTS%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 4 DETERMINANTS MIND MAP.png"
    },
    {
        "name":  "CH 7 INTEGRAL MIND MAP.png",
        "title":  "Chapter 7 Integral Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.2 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 7 INTEGRAL MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%207%20INTEGRAL%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 7 INTEGRAL MIND MAP.png"
    },
    {
        "name":  "CH 8 APPLICATIONS OF INTEGRAL.png",
        "title":  "Chapter 8 Applications Of Integral",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.1 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 8 APPLICATIONS OF INTEGRAL.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%208%20APPLICATIONS%20OF%20INTEGRAL.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 8 APPLICATIONS OF INTEGRAL.png"
    },
    {
        "name":  "CH 9 DIFF EQ MIND MAP.png",
        "title":  "Chapter 9 Diff Eq Mind Map",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.1 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE MIND MAP/CH 9 DIFF EQ MIND MAP.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20MIND%20MAP/CH%209%20DIFF%20EQ%20MIND%20MAP.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE MIND MAP\\CH 9 DIFF EQ MIND MAP.png"
    },
    {
        "name":  "CH 1 RELATIONS AND FUNCTIONS PPT.pptx",
        "title":  "Chapter 1 Relations And Functions",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "17.7 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 1 RELATIONS AND FUNCTIONS PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%201%20RELATIONS%20AND%20FUNCTIONS%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 1 RELATIONS AND FUNCTIONS PPT.pptx"
    },
    {
        "name":  "CH 10 VECTORS PPT.pptx",
        "title":  "Chapter 10 Vectors",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "22.7 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 10 VECTORS PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%2010%20VECTORS%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 10 VECTORS PPT.pptx"
    },
    {
        "name":  "CH 11 3-D PPT.pptx",
        "title":  "Chapter 11 3 D",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "17.6 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 11 3-D PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%2011%203-D%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 11 3-D PPT.pptx"
    },
    {
        "name":  "CH 12 LPP PPT.pptx",
        "title":  "Chapter 12 Lpp",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "18.1 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 12 LPP PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%2012%20LPP%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 12 LPP PPT.pptx"
    },
    {
        "name":  "CH 13 PROBABILITY PPT.pptx",
        "title":  "Chapter 13 Probability",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "15.2 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 13 PROBABILITY PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%2013%20PROBABILITY%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 13 PROBABILITY PPT.pptx"
    },
    {
        "name":  "CH 2 INVERSE T FUNCTIONS PPT.pptx",
        "title":  "Chapter 2 Inverse T Functions",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "11 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 2 INVERSE T FUNCTIONS PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%202%20INVERSE%20T%20FUNCTIONS%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 2 INVERSE T FUNCTIONS PPT.pptx"
    },
    {
        "name":  "CH 3 MATRICES PPT.pptx",
        "title":  "Chapter 3 Matrices",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "18.2 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 3 MATRICES PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%203%20MATRICES%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 3 MATRICES PPT.pptx"
    },
    {
        "name":  "CH 4 DETERMINANTS PPT.pptx",
        "title":  "Chapter 4 Determinants",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "26.4 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 4 DETERMINANTS PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%204%20DETERMINANTS%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 4 DETERMINANTS PPT.pptx"
    },
    {
        "name":  "CH 7 INTEGRALS PPT.pptx",
        "title":  "Chapter 7 Integrals",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "18.7 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 7 INTEGRALS PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%207%20INTEGRALS%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 7 INTEGRALS PPT.pptx"
    },
    {
        "name":  "CH 8 APPLICATIONS OF INTEGRALS.pptx",
        "title":  "Chapter 8 Applications Of Integrals",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "17.2 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 8 APPLICATIONS OF INTEGRALS.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%208%20APPLICATIONS%20OF%20INTEGRALS.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 8 APPLICATIONS OF INTEGRALS.pptx"
    },
    {
        "name":  "CH 9 DIFF EQ PPT.pptx",
        "title":  "Chapter 9 Diff Eq",
        "category":  "slides",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "27.3 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE SLIDE DECK PPT/CH 9 DIFF EQ PPT.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20SLIDE%20DECK%20PPT/CH%209%20DIFF%20EQ%20PPT.pptx",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE SLIDE DECK PPT\\CH 9 DIFF EQ PPT.pptx"
    },
    {
        "name":  "CH 1 RELATIONS AND FN VEDIO.mp4",
        "title":  "Chapter 1 Relations And Fn",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "36.9 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 1 RELATIONS AND FN VEDIO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%201%20RELATIONS%20AND%20FN%20VEDIO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 1 RELATIONS AND FN VEDIO.mp4"
    },
    {
        "name":  "CH 10 VECTORS VEDIO.mp4",
        "title":  "Chapter 10 Vectors",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "30 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 10 VECTORS VEDIO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%2010%20VECTORS%20VEDIO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 10 VECTORS VEDIO.mp4"
    },
    {
        "name":  "CH 11 3-D VEDIO.mp4",
        "title":  "Chapter 11 3 D",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "36.2 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 11 3-D VEDIO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%2011%203-D%20VEDIO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 11 3-D VEDIO.mp4"
    },
    {
        "name":  "CH 12 LPP VEDIO.mp4",
        "title":  "Chapter 12 Lpp",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "19.2 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 12 LPP VEDIO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%2012%20LPP%20VEDIO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 12 LPP VEDIO.mp4"
    },
    {
        "name":  "CH 13 PROBABILITY VEDIO.mp4",
        "title":  "Chapter 13 Probability",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "34.7 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 13 PROBABILITY VEDIO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%2013%20PROBABILITY%20VEDIO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 13 PROBABILITY VEDIO.mp4"
    },
    {
        "name":  "CH 3 MATRICES VIDEO.mp4",
        "title":  "Chapter 3 Matrices Video",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "31.3 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 3 MATRICES VIDEO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%203%20MATRICES%20VIDEO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 3 MATRICES VIDEO.mp4"
    },
    {
        "name":  "CH 4 DETERMINANTS VIDEO.mp4",
        "title":  "Chapter 4 Determinants Video",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "31.6 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 4 DETERMINANTS VIDEO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%204%20DETERMINANTS%20VIDEO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 4 DETERMINANTS VIDEO.mp4"
    },
    {
        "name":  "CH 7 INTEGRALS.mp4",
        "title":  "Chapter 7 Integrals",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "37.1 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 7 INTEGRALS.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%207%20INTEGRALS.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 7 INTEGRALS.mp4"
    },
    {
        "name":  "CH 8 APPLICATION OF INTEGRAL.mp4",
        "title":  "Chapter 8 Application Of Integral",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "31 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 8 APPLICATION OF INTEGRAL.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%208%20APPLICATION%20OF%20INTEGRAL.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 8 APPLICATION OF INTEGRAL.mp4"
    },
    {
        "name":  "CH 9 DIFF EQ VEDIO.mp4",
        "title":  "Chapter 9 Diff Eq",
        "category":  "videos",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "17.9 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/interactive l plans/INTERACTIVE VIDEO/CH 9 DIFF EQ VEDIO.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/interactive%20l%20plans/INTERACTIVE%20VIDEO/CH%209%20DIFF%20EQ%20VEDIO.mp4",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\interactive l plans\\INTERACTIVE VIDEO\\CH 9 DIFF EQ VEDIO.mp4"
    },
    {
        "name":  "mind map determinants.png",
        "title":  "Mind Map Determinants",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "866.3 KB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/notes/mind map determinants.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/notes/mind%20map%20determinants.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\notes\\mind map determinants.png"
    },
    {
        "name":  "mind map inverse t functions.png",
        "title":  "Mind Map Inverse T Functions",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1006.2 KB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/notes/mind map inverse t functions.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/notes/mind%20map%20inverse%20t%20functions.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\notes\\mind map inverse t functions.png"
    },
    {
        "name":  "mind map matrices.png",
        "title":  "Mind Map Matrices",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.6 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/notes/mind map matrices.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/notes/mind%20map%20matrices.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\notes\\mind map matrices.png"
    },
    {
        "name":  "mindmap ch6.png",
        "title":  "Mindmap Ch6",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "1.5 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/notes/mindmap ch6.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/notes/mindmap%20ch6.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\notes\\mindmap ch6.png"
    },
    {
        "name":  "mindmap probability.png",
        "title":  "Mindmap Probability",
        "category":  "mindmaps",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "2.6 MB",
        "isLarge":  false,
        "localLink":  "file:///C:/Users/kirti/Dropbox/12 ALL TEACHING LEARNING CONTENT/notes/mindmap probability.png",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/notes/mindmap%20probability.png",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\notes\\mindmap probability.png"
    },
    {
        "name":  "Solution PB1 2025.html",
        "title":  "Solution Pb1 2025",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "95.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/Solution PB1 2025.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/PB1%20QP/Solution%20PB1%202025.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\PB1 QP\\Solution PB1 2025.html"
    },
    {
        "name":  "12 maths study material.html",
        "title":  "12 Maths Study Material",
        "category":  "html",
        "class":  "Class 12",
        "classKey":  "class12",
        "size":  "79.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class12/12 maths study material.html",
        "dropboxUrl":  "https://www.dropbox.com/home/12%20ALL%20TEACHING%20LEARNING%20CONTENT/REMEDIAL%20AND%20EXTRA%20CLASS%20WINTER%202025/2025/12%20maths%20study%20material.html",
        "path":  "12 ALL TEACHING LEARNING CONTENT\\REMEDIAL AND EXTRA CLASS WINTER 2025\\2025\\12 maths study material.html"
    },
    {
        "name":  "CLASS TEST CH 1 7MATH.html",
        "title":  "Class Test Chapter 1 7Math",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "12.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/CLASS TEST CH 1 7MATH.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%201/CLASS%20TEST%20CH%201%207MATH.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 1\\CLASS TEST CH 1 7MATH.html"
    },
    {
        "name":  "CLASS TEST CH 1.html",
        "title":  "Class Test Chapter 1",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "17.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/CLASS TEST CH 1.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%201/CLASS%20TEST%20CH%201.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 1\\CLASS TEST CH 1.html"
    },
    {
        "name":  "LARGE NUMBERS AROUND US (2).html",
        "title":  "Large Numbers Around Us (2)",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "26.6 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/LARGE NUMBERS AROUND US (2).html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%201/LARGE%20NUMBERS%20AROUND%20US%20(2).html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 1\\LARGE NUMBERS AROUND US (2).html"
    },
    {
        "name":  "ch2 activities class 7.html",
        "title":  "Ch2 Activities Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "29 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ch2 activities class 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%202/ch2%20activities%20class%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 2\\ch2 activities class 7.html"
    },
    {
        "name":  "worksheet ch2.html",
        "title":  "Worksheet Ch2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "25.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet ch2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%202/worksheet%20ch2.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 2\\worksheet ch2.html"
    },
    {
        "name":  "ACTIVITIES CH3 CLASS 7.html",
        "title":  "Activities Ch3 Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "18.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ACTIVITIES CH3 CLASS 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%203/ACTIVITIES%20CH3%20CLASS%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 3\\ACTIVITIES CH3 CLASS 7.html"
    },
    {
        "name":  "ch3 class 7 activities and worksheet.html",
        "title":  "Ch3 Class 7 Activities And Worksheet",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "24.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ch3 class 7 activities and worksheet.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%203/ch3%20class%207%20activities%20and%20worksheet.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 3\\ch3 class 7 activities and worksheet.html"
    },
    {
        "name":  "interactive activity ch-4.html",
        "title":  "Interactive Activity Chapter 4",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "56.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/interactive activity ch-4.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%204/interactive%20activity%20ch-4.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 4\\interactive activity ch-4.html"
    },
    {
        "name":  "interactive activity ch4.html",
        "title":  "Interactive Activity Ch4",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "25.7 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/interactive activity ch4.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%204/interactive%20activity%20ch4.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 4\\interactive activity ch4.html"
    },
    {
        "name":  "activitiesch5.html",
        "title":  "Activitiesch5",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "60.7 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/activitiesch5.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%205/activitiesch5.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 5\\activitiesch5.html"
    },
    {
        "name":  "worksheet.html",
        "title":  "Worksheet",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "19.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%205/worksheet.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 5\\worksheet.html"
    },
    {
        "name":  "worksheet2.html",
        "title":  "Worksheet2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "22.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%205/worksheet2.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 5\\worksheet2.html"
    },
    {
        "name":  "ACT2.html",
        "title":  "Act2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "23.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ACT2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%206/ACT2.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 6\\ACT2.html"
    },
    {
        "name":  "activity class 7 ch6.html",
        "title":  "Activity Class 7 Ch6",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "57.7 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/activity class 7 ch6.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%206/activity%20class%207%20ch6.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 6\\activity class 7 ch6.html"
    },
    {
        "name":  "maths worksheet ch6 2.html",
        "title":  "Maths Worksheet Ch6 2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "28.2 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/maths worksheet ch6 2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%206/maths%20worksheet%20ch6%202.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 6\\maths worksheet ch6 2.html"
    },
    {
        "name":  "Number_Play.mp4",
        "title":  "Number Play",
        "category":  "videos",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "38.9 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/7 ALL TEACHING LEARNING CONTENT/Chapter 6/Number_Play.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%206/Number_Play.mp4",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 6\\Number_Play.mp4"
    },
    {
        "name":  "worsheet ch6 1.html",
        "title":  "Worsheet Ch6 1",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "12.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worsheet ch6 1.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%206/worsheet%20ch6%201.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 6\\worsheet ch6 1.html"
    },
    {
        "name":  "activities.html",
        "title":  "Activities",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "28.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/activities.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%207/activities.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 7\\activities.html"
    },
    {
        "name":  "main file.html",
        "title":  "Main File",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "54.4 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/main file.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%207/main%20file.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 7\\main file.html"
    },
    {
        "name":  "notes.html",
        "title":  "Notes",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "24 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/notes.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%207/notes.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 7\\notes.html"
    },
    {
        "name":  "worksheet.html",
        "title":  "Worksheet",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "24.4 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Chapter%208/worksheet.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Chapter 8\\worksheet.html"
    },
    {
        "name":  "class 7  class test analysis.html",
        "title":  "Class 7  Class Test Analysis",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "16.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/class 7  class test analysis.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Test/class%207%20%20class%20test%20analysis.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Class Test\\class 7  class test analysis.html"
    },
    {
        "name":  "CLASS TEST CH 1 7MATH.html",
        "title":  "Class Test Chapter 1 7Math",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "12.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/CLASS TEST CH 1 7MATH.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Test/CLASS%20TEST%20CH%201%207MATH.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Class Test\\CLASS TEST CH 1 7MATH.html"
    },
    {
        "name":  "CLASS TEST CH 1.html",
        "title":  "Class Test Chapter 1",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "17.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/CLASS TEST CH 1.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Test/CLASS%20TEST%20CH%201.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Class Test\\CLASS TEST CH 1.html"
    },
    {
        "name":  "class test ch03 class 7.html",
        "title":  "Class Test Ch03 Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "16.2 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/class test ch03 class 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Test/class%20test%20ch03%20class%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Class Test\\class test ch03 class 7.html"
    },
    {
        "name":  "test ch2 class 7.html",
        "title":  "Test Ch2 Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "15.1 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/test ch2 class 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Test/test%20ch2%20class%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Class Test\\test ch2 class 7.html"
    },
    {
        "name":  "test class 6 basic.html",
        "title":  "Test Class 6 Basic",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "14.6 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/test class 6 basic.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/Class%20Test/test%20class%206%20basic.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\Class Test\\test class 6 basic.html"
    },
    {
        "name":  "CT Module 1 for 7C.html",
        "title":  "Ct Module 1 For 7C",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "19.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/CT Module 1 for 7C.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/CT/CT%20Module%201%20for%207C.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\CT\\CT Module 1 for 7C.html"
    },
    {
        "name":  "class 7 holiday home work winter.html",
        "title":  "Class 7 Holiday Home Work Winter",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "34 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/class 7 holiday home work winter.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/HW/class%207%20holiday%20home%20work%20winter.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\HW\\class 7 holiday home work winter.html"
    },
    {
        "name":  "MDP CLASS 7.html",
        "title":  "Mdp Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "38.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/MDP CLASS 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/MDP/MDP%20CLASS%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\MDP\\MDP CLASS 7.html"
    },
    {
        "name":  "readiness module for class 7.html",
        "title":  "Readiness Module For Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "27.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/readiness module for class 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/MISC/readiness%20module%20for%20class%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\MISC\\readiness module for class 7.html"
    },
    {
        "name":  "LARGE NUMBERS AROUND US (2).html",
        "title":  "Large Numbers Around Us (2)",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "26.6 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/LARGE NUMBERS AROUND US (2).html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%201/LARGE%20NUMBERS%20AROUND%20US%20(2).html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 1\\LARGE NUMBERS AROUND US (2).html"
    },
    {
        "name":  "ch2 activities class 7.html",
        "title":  "Ch2 Activities Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "29 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ch2 activities class 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%202/ch2%20activities%20class%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 2\\ch2 activities class 7.html"
    },
    {
        "name":  "worksheet ch2.html",
        "title":  "Worksheet Ch2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "25.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet ch2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%202/worksheet%20ch2.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 2\\worksheet ch2.html"
    },
    {
        "name":  "ACTIVITIES CH3 CLASS 7.html",
        "title":  "Activities Ch3 Class 7",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "18.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ACTIVITIES CH3 CLASS 7.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%203/ACTIVITIES%20CH3%20CLASS%207.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 3\\ACTIVITIES CH3 CLASS 7.html"
    },
    {
        "name":  "ch3 class 7 activities and worksheet.html",
        "title":  "Ch3 Class 7 Activities And Worksheet",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "24.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ch3 class 7 activities and worksheet.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%203/ch3%20class%207%20activities%20and%20worksheet.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 3\\ch3 class 7 activities and worksheet.html"
    },
    {
        "name":  "interactive activity ch-4.html",
        "title":  "Interactive Activity Chapter 4",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "56.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/interactive activity ch-4.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%204/interactive%20activity%20ch-4.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 4\\interactive activity ch-4.html"
    },
    {
        "name":  "activitiesch5.html",
        "title":  "Activitiesch5",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "60.7 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/activitiesch5.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%205/activitiesch5.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 5\\activitiesch5.html"
    },
    {
        "name":  "Geometric_Blueprint.pptx",
        "title":  "Geometric Blueprint",
        "category":  "slides",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "17.7 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/7 ALL TEACHING LEARNING CONTENT/PART 1/Chapter 5/Geometric_Blueprint.pptx",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%205/Geometric_Blueprint.pptx",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 5\\Geometric_Blueprint.pptx"
    },
    {
        "name":  "How_to_Create_Perfect_Parallel_Lines_(2_Methods).mp4",
        "title":  "How To Create Perfect Parallel Lines (2 Methods)",
        "category":  "videos",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "26.7 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/7 ALL TEACHING LEARNING CONTENT/PART 1/Chapter 5/How_to_Create_Perfect_Parallel_Lines_(2_Methods).mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%205/How_to_Create_Perfect_Parallel_Lines_(2_Methods).mp4",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 5\\How_to_Create_Perfect_Parallel_Lines_(2_Methods).mp4"
    },
    {
        "name":  "worksheet.html",
        "title":  "Worksheet",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "19.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%205/worksheet.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 5\\worksheet.html"
    },
    {
        "name":  "worksheet2.html",
        "title":  "Worksheet2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "22.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%205/worksheet2.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 5\\worksheet2.html"
    },
    {
        "name":  "ACT2.html",
        "title":  "Act2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "23.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/ACT2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%206/ACT2.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 6\\ACT2.html"
    },
    {
        "name":  "activity class 7 ch6.html",
        "title":  "Activity Class 7 Ch6",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "57.7 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/activity class 7 ch6.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%206/activity%20class%207%20ch6.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 6\\activity class 7 ch6.html"
    },
    {
        "name":  "maths worksheet ch6 2.html",
        "title":  "Maths Worksheet Ch6 2",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "28.2 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/maths worksheet ch6 2.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%206/maths%20worksheet%20ch6%202.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 6\\maths worksheet ch6 2.html"
    },
    {
        "name":  "Number_Play.mp4",
        "title":  "Number Play",
        "category":  "videos",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "38.9 MB",
        "isLarge":  true,
        "localLink":  "file:///C:/Users/kirti/Dropbox/7 ALL TEACHING LEARNING CONTENT/PART 1/Chapter 6/Number_Play.mp4",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%206/Number_Play.mp4",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 6\\Number_Play.mp4"
    },
    {
        "name":  "worsheet ch6 1.html",
        "title":  "Worsheet Ch6 1",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "12.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worsheet ch6 1.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%206/worsheet%20ch6%201.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 6\\worsheet ch6 1.html"
    },
    {
        "name":  "activities.html",
        "title":  "Activities",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "28.9 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/activities.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%207/activities.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 7\\activities.html"
    },
    {
        "name":  "main file.html",
        "title":  "Main File",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "54.4 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/main file.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%207/main%20file.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 7\\main file.html"
    },
    {
        "name":  "notes.html",
        "title":  "Notes",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "24 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/notes.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%207/notes.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 7\\notes.html"
    },
    {
        "name":  "worksheet.html",
        "title":  "Worksheet",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "24.4 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/PART%201/Chapter%208/worksheet.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\PART 1\\Chapter 8\\worksheet.html"
    },
    {
        "name":  "chapter 1 act.html",
        "title":  "Chapter 1 Act",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "87 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/chapter 1 act.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/CH%201/chapter%201%20act.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\CH 1\\chapter 1 act.html"
    },
    {
        "name":  "worksheet ch-1.html",
        "title":  "Worksheet Chapter 1",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "13.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet ch-1.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/CH%201/worksheet%20ch-1.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\CH 1\\worksheet ch-1.html"
    },
    {
        "name":  "chapter 3.html",
        "title":  "Chapter 3",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "48.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/chapter 3.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/CH%203/chapter%203.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\CH 3\\chapter 3.html"
    },
    {
        "name":  "worksheet chapter 3 part 2 f.html",
        "title":  "Worksheet Chapter 3 Part 2 F",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "70.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet chapter 3 part 2 f.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/CH%203/worksheet%20chapter%203%20part%202%20f.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\CH 3\\worksheet chapter 3 part 2 f.html"
    },
    {
        "name":  "chapter 1 act.html",
        "title":  "Chapter 1 Act",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "87 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/chapter 1 act.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/gegp1dd/chapter%201%20act.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\gegp1dd\\chapter 1 act.html"
    },
    {
        "name":  "chapter 3.html",
        "title":  "Chapter 3",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "48.8 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/chapter 3.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/gegp1dd/chapter%203.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\gegp1dd\\chapter 3.html"
    },
    {
        "name":  "worksheet ch-1.html",
        "title":  "Worksheet Chapter 1",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "13.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet ch-1.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/gegp1dd/worksheet%20ch-1.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\gegp1dd\\worksheet ch-1.html"
    },
    {
        "name":  "worksheet chapter 3 part 2 f.html",
        "title":  "Worksheet Chapter 3 Part 2 F",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "70.5 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/worksheet chapter 3 part 2 f.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/part%202/gegp1dd/worksheet%20chapter%203%20part%202%20f.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\part 2\\gegp1dd\\worksheet chapter 3 part 2 f.html"
    },
    {
        "name":  "revision worksheet part1 SEE.html",
        "title":  "Revision Worksheet Part1 See",
        "category":  "html",
        "class":  "Class 7",
        "classKey":  "class7",
        "size":  "32 KB",
        "isLarge":  false,
        "localLink":  "interactive lesson plans/class7/revision worksheet part1 SEE.html",
        "dropboxUrl":  "https://www.dropbox.com/home/7%20ALL%20TEACHING%20LEARNING%20CONTENT/sample%20paper%20SSE%202026/revision%20worksheet%20part1%20SEE.html",
        "path":  "7 ALL TEACHING LEARNING CONTENT\\sample paper SSE 2026\\revision worksheet part1 SEE.html"
    }
];
